import type { Metadata } from 'next'
import UikitProvider from '@repo/ui-kit/UiKitProvider'
import Root from '@repo/ui-kit/Root'
import './layout.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="body-t">
        <Root>
          <UikitProvider> {children}</UikitProvider>
        </Root>
      </body>
    </html>
  )
}
