import { type EnumList } from '@type/Enums'

export enum Banks {
  TEJARAT = 'TEJARAT',
  KHAWERMIANEH = 'KHAWERMIANEH',
  SAMAN = 'SAMAN',
  ANSAR = 'ANSAR',
  GHAVAMIN = 'GHAVAMIN',
  EGHTESAD_NOVIN = 'EGHTESAD_NOVIN',
  PARSIAN = 'PARSIAN',
  PASARGAD = 'PASARGAD',
  POST_BANK = 'POST_BANK',
  TOSE_SADERAT = 'TOSE_SADERAT',
  REFAH = 'REFAH',
  SEPAH = 'SEPAH',
  SARMAYEH = 'SARMAYEH',
  SADERAT = 'SADERAT',
  SANAT_MADAN = ' SANAT_MADAN',
  KARAFARIN = 'KARAFARIN',
  MASKAN = 'MASKAN',
  MELAT = 'MELAT',
  MELLI = 'MELLI',
  SINA = 'SINA',
  TOSEH = 'TOSEH',
  RESALAT = 'RESALAT',
  GARDESHGARI = 'GARDESHGARI',
  AYANDEH = 'AYANDEH',
  SHAHR = 'SHAHR',
  GHARZOLHASANEH_MEHR = 'GHARZOLHASANEH_MEHR',
  TOSEH_TAAVON = 'TOSEH_TAAVON',
  HEKMAT_IRANIAN = 'HEKMAT_IRANIAN',
  KOSAR = 'KOSAR',
  MELAL = 'MELAL',
  DEY = 'DEY',
  IRAN_ZAMIN = ' IRAN_ZAMIN',
  MARKAZI = 'MARKAZI',
  KESHAVARZI = 'KESHAVARZI',
  NOOR = 'NOOR',
  COBALT = 'COBALT'
}

export const BankNamesList: EnumList = [
  { value: Banks.TEJARAT, title: 'تجارت', color: 'default' },
  { value: Banks.KHAWERMIANEH, title: 'خاورمیانه', color: 'default' },
  { value: Banks.SAMAN, title: 'سامان', color: 'default' },
  { value: Banks.ANSAR, title: 'انصار', color: 'default' },
  { value: Banks.GHAVAMIN, title: 'قوامین', color: 'default' },
  { value: Banks.EGHTESAD_NOVIN, title: 'اقتصادنوین', color: 'default' },
  { value: Banks.PARSIAN, title: 'پارسیان', color: 'default' },
  { value: Banks.PASARGAD, title: 'پاسارگاد', color: 'default' },
  { value: Banks.POST_BANK, title: 'پست بانک', color: 'default' },
  { value: Banks.TOSE_SADERAT, title: 'توسعه صادرات', color: 'default' },
  { value: Banks.REFAH, title: 'رفاه', color: 'default' },
  { value: Banks.SEPAH, title: 'سپه', color: 'default' },
  { value: Banks.SARMAYEH, title: 'سرمایه', color: 'default' },
  { value: Banks.SADERAT, title: 'صادرات', color: 'default' },
  { value: Banks.SANAT_MADAN, title: 'صنعت و معدن', color: 'default' },
  { value: Banks.KARAFARIN, title: 'کارآفرین', color: 'default' },
  { value: Banks.MASKAN, title: 'مسکن', color: 'default' },
  { value: Banks.MELAT, title: 'ملت', color: 'default' },
  { value: Banks.MELLI, title: 'ملی ایران', color: 'default' },
  { value: Banks.SINA, title: 'سینا', color: 'default' },
  { value: Banks.TOSEH, title: 'موسسه مالی توسعه', color: 'default' },
  { value: Banks.RESALAT, title: 'رسالت', color: 'default' },
  { value: Banks.GARDESHGARI, title: 'گردشگری', color: 'default' },
  { value: Banks.AYANDEH, title: 'آینده', color: 'default' },
  { value: Banks.SHAHR, title: 'شهر', color: 'default' },
  { value: Banks.GHARZOLHASANEH_MEHR, title: 'قرض الحسنه مهر', color: 'default' },
  { value: Banks.TOSEH_TAAVON, title: 'توسعه تعاون', color: 'default' },
  { value: Banks.HEKMAT_IRANIAN, title: 'حکمت ایرانیان', color: 'default' },
  { value: Banks.KOSAR, title: 'موسسه کوثر', color: 'default' },
  { value: Banks.MELAL, title: 'موسسه اعتباری ملل', color: 'default' },
  { value: Banks.DEY, title: 'دی', color: 'default' },
  { value: Banks.IRAN_ZAMIN, title: 'ایران زمین', color: 'default' },
  { value: Banks.MARKAZI, title: 'مرکزی', color: 'default' },
  { value: Banks.KESHAVARZI, title: 'کشاورزی', color: 'default' },
  { value: Banks.NOOR, title: 'موسسه اعتباری نور', color: 'default' },
  { value: Banks.COBALT, title: 'کبالت', color: 'default' }
]
