export enum BooleanPlus {
  Null = 'NUll',
  NA = 'INITIALIZED',
  REQUESTED = 'REQUESTED',
  GRANTED = 'GRANTED',
  REJECTED = 'REJECTED',
  CANCELED = 'CANCELED',
  RETURNED = 'RETURNED_FOR_UPDATE',
  WITHDREW = 'WITHDREW',
  CONFIRMED = 'CONFIRMED'
}
