import type { Metadata } from 'next'
import Theme from './theme'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import { NextIntlClientProvider } from 'next-intl'
import { unstable_setRequestLocale } from 'next-intl/server'
import { defaultLocale } from '@/i18n'
import { pelak } from './font'

export const metadata: Metadata = {
  title: 'Feeleasy',
  description: 'Generated by create next app',
  robots: '/robots.text'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
  params?: { locale: string }
}>) {
  unstable_setRequestLocale(defaultLocale)

  let messages
  try {
    messages = (await import(`../../messages/${defaultLocale}.json`)).default
  } catch (error) {
    console.error('Failed to load messages:', error)
  }

  return (
    <html lang={defaultLocale} dir="rtl" className={`${pelak.variable}`}>
      <body>
        <AppRouterCacheProvider>
          <NextIntlClientProvider locale={defaultLocale} messages={messages}>
            <Theme>
              <div id="root-layout">{children}</div>
            </Theme>
          </NextIntlClientProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
